### ISSUE TITLE
It doesn't send card when user join only sends messages when user leaves

### ISSUE THREAD

**Issue by mrayan980** [AdvicSaha443/Discord.py-Welcoming-Users#1]
Join gives no error yet it also doesnt work

@client.event
async def on_member_join(member):
  channel = client.get_channel(1053950140542623815)

  pos = sum(m.joined_at < member.joined_at for m in member.guild.members if m.joined_at is not None)

  if pos == 1:
    te = "st"
  elif pos == 2:
    te = "nd"
  elif pos == 3:
    te = "rd"
  else: te = "th"

  background = Editor("Typer.jpg")
  profile_image = await load_image_async(str(member.avatar.url))

  profile = Editor(profile_image).resize((150, 150)).circle_image()
  poppins = Font.poppins(size=50, variant="bold")

  poppins_small = Font.poppins(size=20, variant="light")

  background.paste(profile, (325, 90))
  background.ellipse((325, 90), 150, 150, outline="gold", stroke_width=4)

  background.text((400, 260), f"WELCOME TO {member.guild.name}", color="white", font=poppins, align="center")
  background.text((400, 325), f"{member.name}#{member.discriminator}", color="white", font=poppins_small, align="center")
  background.text((400, 360), f"You Are The {pos}{te} Member", color="#0BE7F5", font=poppins_small, align="center")

  file = File(fp=background.image_bytes, filename="Typer.jpg")

  #if you want to message more message then you can add like this
  await channel.send(f"Heya {member.mention}! Welcome To **{member.guild.name} For More Information Go To <#885152158599770183>**")

  #for sending the card
  await channel.send(file=file)

**Comment by AdvicSaha443** [comment]
Line 38, avatar_url was removed in 2.0,  
click [here](https://discordpy.readthedocs.io/en/stable/api.html#discord.Member) for more information

you can replace that line to: 
**profile_image = await load_image_async(str(member.display_avatar.url))**
